### ISSUE TITLE
Question: May I add this package to the Arch Linux User Repository (AUR)?

### ISSUE THREAD

**Issue by ShapeShifter499** [jsageryd/gaku#3]
Someone on the Freenode channel ##Japanese just suggested this to me. I don't see this package on Arch Linux so I was wondering if I could package this for the Arch Linux User Repository (AUR). I'm just starting out to learn Japanese and I think this would be a neat package to have for the AUR. The AUR is a collection of clever scripts that auto fetch code and install it properly. My package would fetch the latest code from here and make it a bit easier for others to get automatic updates. If my package on AUR gets enough votes it might be accepted into the official community repository.

**Comment by jsageryd** [comment]
If that makes your life easier, I don't see why not. Feel free to. I'm not an Arch user though, so I would not be able to do any kind of maintenance of it.
